# Pandas Overview

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.datasets import load_iris

In [3]:
REPO_ROOT = Path.cwd().parents[1]
DATA_DIR = REPO_ROOT / "data"

## Series
<hr/>

#### Intuition

1-dimensional labeled array

#### Initialization

- **list**: values, indices
- **dict**: keys -> indices, values -> values

In [4]:
my_list = np.array([i for i in range(5)])
indices = [chr(c) for c in range(ord("a"), ord("a") + 5)]

series = pd.Series(
    my_list,
    index=indices,
    dtype=np.int32,
)
print(series)

other_indices = [chr(c) for c in range(ord("A"), ord("A") + 5)]
my_dict = {name: value for (name, value) in zip(other_indices, my_list * 2)}

series1 = pd.Series(my_dict, dtype=np.int32)
print(series1)

a    0
b    1
c    2
d    3
e    4
dtype: int32
A    0
B    2
C    4
D    6
E    8
dtype: int32

#### Element accessing

- **loc**: provide id (location by label)
- **iloc**: provide position (int location)

In [5]:
print(series["a"])  # 0
print(series.loc["b"])  # 1
print(series.iloc[2])  # 2
print("Filter by value")
print(series[series > 2])

0
1
2
Filter by value
d    3
e    4
dtype: int32

## Dataframe

#### Intuition

Tabular data structure with rows & columns like 2-dimensional array

#### Initialization

- **dict[Any, list[Any]]**: keys -> columns, values -> items
- **np.array**: 2 dimensional numpy array 
- files like **csv**, **json** etc
- **sklearn datasets**

In [6]:
my_dict = {
    "course": ["DiffEq", "ProgTech", "Circuits"],
    "grade": [8, 10, 10],
}

grades = pd.DataFrame(my_dict)
grades

     course  grade
0    DiffEq      8
1  ProgTech     10
2  Circuits     10

In [7]:
# important for reproducibility
np.random.seed(42)

# data
array = np.random.random((3, 4))
columns = np.array(["a", "b", "c", "d"])
rows = np.array([1, 2, 3])

df = pd.DataFrame(data=array, index=rows, columns=columns)
df

          a         b         c         d
1  0.374540  0.950714  0.731994  0.598658
2  0.156019  0.155995  0.058084  0.866176
3  0.601115  0.708073  0.020584  0.969910

In [8]:
pd.read_csv(DATA_DIR / "mini_csv.csv", index_col="ID")

    interest  knowledge  helped_learning  rating
ID
1          5          6                5       5
2          7          7                7       7
3          2          5                3       4
4          6          6                6       6
5          6          7                6       7
6          3          5                5       4
7          7          7                6       7
8          5          5                4       5
9          7          7                6       6

In [9]:
dataset = load_iris()
iris_df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
iris_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

#### Quick data overview

- **head**: gives the first 5 rows (similar: *tail*, *sample*)
- **info**: general info 
- **describe**: returns important statistics
- **columns**: column names
- **index**: row names
- **shape**
- **dtypes**: per column data types  
- **corr**: correlation matrix *important for feature selection*
- **isna**: returns boolean df (similar: *notna*, useful: *df.isna().sum()* )

In [10]:
iris_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
iris_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [12]:
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [13]:
print(f"Column names: {iris_df.columns}")

Column names: Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [14]:
print(f"Row names: {iris_df.index}")

Row names: RangeIndex(start=0, stop=150, step=1)

In [15]:
print(f"Shape: {iris_df.shape}")

Shape: (150, 4)

In [16]:
print(f"Data types: {iris_df.dtypes}")

Data types: sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

In [17]:
iris_df.corr()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
sepal length (cm),1.000000,-0.117570,0.871754,0.817941
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126
petal length (cm),0.871754,-0.428440,1.000000,0.962865
petal width (cm),0.817941,-0.366126,0.962865,1.000000

#### Element accessing

- **operator[]**
- **loc**
- **iloc**

Note that we can use:
- loc[*row_indexer*, *column_indexer*]
- lists as indexers
- slicing

In [18]:
grades["course"]

0      DiffEq
1    ProgTech
2    Circuits
Name: course, dtype: str

In [19]:
grades[["course", "grade"]]

     course  grade
0    DiffEq      8
1  ProgTech     10
2  Circuits     10

In [20]:
grades.loc[:, "course"]

0      DiffEq
1    ProgTech
2    Circuits
Name: course, dtype: str

In [21]:
# column_indexer is ommited => :
# this doesn't work for row_indexer
grades.loc[0]

course    DiffEq
grade          8
Name: 0, dtype: object

#### Mutability

- add / remove columns / rows
- mutate records

*Always assign*

In [22]:
# new col
grades["difficulty"] = np.array([5, 4, 3])
grades

     course  grade  difficulty
0    DiffEq      8           5
1  ProgTech     10           4
2  Circuits     10           3

In [23]:
# new row
new_row = pd.DataFrame(
    [
        {
            "course": "Semiconductors",
            "grade": 9,
            "difficulty": 3,
        }
    ],  # list object indicates that there could be more rows to add
    index=[3],
)  # always specify, since default is 0
grades = pd.concat([grades, new_row])

grades

           course  grade  difficulty
0          DiffEq      8           5
1        ProgTech     10           4
2        Circuits     10           3
3  Semiconductors      9           3

In [24]:
# record edit
grades.loc[3, "grade"] = 10
grades

           course  grade  difficulty
0          DiffEq      8           5
1        ProgTech     10           4
2        Circuits     10           3
3  Semiconductors     10           3

In [25]:
courses = grades.drop(columns=["grade"])
courses

           course  difficulty
0          DiffEq           5
1        ProgTech           4
2        Circuits           3
3  Semiconductors           3

#### Filtering

df[ df[ *features* ] matches conditions]

c style logical operators *( &, | )*

In [26]:
grades[grades["difficulty"] > 3]

     course  grade  difficulty
0    DiffEq      8           5
1  ProgTech     10           4

#### Aggregate functions

Summarize a set of values

Examples:<br/>
mean, median, std, min, mode, max, sum, count, value_counts

In [27]:
grades.mean(numeric_only=True)

grade         9.50
difficulty    3.75
dtype: float64

In [28]:
grades["difficulty"].value_counts()

difficulty
3    2
5    1
4    1
Name: count, dtype: int64

Groupby

In [29]:
group = grades.groupby("difficulty")
group["grade"].mean()

difficulty
3    10.0
4    10.0
5     8.0
Name: grade, dtype: float64

#### Data Cleaning

- *drop*: drops specified cols / rows
- *dropna*: drops the cols / rows with na (not available) values
- *fillna*: fills na with input
- *drop_duplicates*: drops duplicate rows

In [30]:
grades.loc[4, "course"] = "Analysis"
grades

           course  grade  difficulty
0          DiffEq    8.0         5.0
1        ProgTech   10.0         4.0
2        Circuits   10.0         3.0
3  Semiconductors   10.0         3.0
4        Analysis    NaN         NaN

Note that ints were converted to floats.<br/>
That is caused by the addition of NaN values because pandas cannot store them as int

*Reminder*: The following lines don't change the original df because we have to assign

important **dropna** args:
- how: 'any' | 'all' => if `how`(na) drop
- thresh: at least `thresh` na vals to drop
- subset: select cols / rows

In [31]:
grades.dropna(subset="grade")

           course  grade  difficulty
0          DiffEq    8.0         5.0
1        ProgTech   10.0         4.0
2        Circuits   10.0         3.0
3  Semiconductors   10.0         3.0

Common fill values:
- 0 / -1
- None
- mean / median / mode

In [32]:
grades.fillna({"grade": -1})  # fillna(-1) fills all nan values

           course  grade  difficulty
0          DiffEq    8.0         5.0
1        ProgTech   10.0         4.0
2        Circuits   10.0         3.0
3  Semiconductors   10.0         3.0
4        Analysis   -1.0         NaN

Fill functions:
- **ffill**: forward fill
    - Copies the *last* valid value forward to next missing rows.
    - Sequential data where values stay the same until they change (e.g., status, price tiers).
- **bfill**: backward fill
    - Copies the *next* valid value backward to previous missing rows.
    - Situations where you need to look ahead to fill current gaps.
- **interpolation**
    - Estimates values by drawing a line or curve between surrounding valid points.
    - Continuous, numeric data with mathematical trends (e.g., temperature, stock trends).

#### Transformation functions

- **apply**: applies a function along an axis
- **map**: applies a function element-wise
- **replace**: replaces values according to given dictionary
- **clip**: caps outliers by limiting values to a specified range
- **pd.cut**: Segments data into equal-*width* intervals
- **pd.qcut**: Segments data into equal-*size* intervals (quantiles)
- **pd.get_dummies**: one hot encoding
- **pd.factorize**: label encoding

In [33]:
mean_diff = courses.loc[:, "difficulty"].mean()
courses["difficulty"] = courses["difficulty"].map(
    lambda d: "hard" if d > mean_diff else "easy"
)
# or: courses["difficulty"] = np.where(courses["difficulty"] > mean_diff, 'hard', 'easy')
courses

           course difficulty
0          DiffEq       hard
1        ProgTech       hard
2        Circuits       easy
3  Semiconductors       easy

In [34]:
courses["difficulty"].replace({"hard": 1, "easy": 0})

0    1
1    1
2    0
3    0
Name: difficulty, dtype: object

In [35]:
pd.cut(iris_df["sepal length (cm)"], bins=3, labels=["low", "mid", "high"]).head()

0    low
1    low
2    low
3    low
4    low
Name: sepal length (cm), dtype: category
Categories (3, str): ['low' < 'mid' < 'high']